export const MANIFEST_SCHEMA_VERSION = 1;

export const DISPATCH_MANIFEST_SCHEMA = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://omnivm.dev/schemas/dispatch-manifest.v1.schema.json",
  title: "OmniVM Dispatch Manifest",
  type: "object",
  additionalProperties: false,
  required: ["version", "defaultRuntime", "ops"],
  properties: {
    version: { const: MANIFEST_SCHEMA_VERSION },
    defaultRuntime: { type: "string" },
    source: { type: "string" },
    ops: {
      type: "array",
      items: { $ref: "#/$defs/ManifestOp" },
    },
    bridges: {
      type: "array",
      items: { $ref: "#/$defs/ManifestBridgeOp" },
    },
    typeSummary: { $ref: "#/$defs/ManifestTypeSummary" },
    diagnostics: {
      type: "array",
      items: { $ref: "#/$defs/ManifestDiagnostic" },
    },
  },
  $defs: {
    CaptureMap: {
      type: "object",
      additionalProperties: { type: "string" },
    },
    ManifestValue: {
      oneOf: [
        {
          type: "object",
          required: ["kind", "value"],
          properties: {
            kind: { const: "literal" },
            value: {},
          },
          additionalProperties: false,
        },
        {
          type: "object",
          required: ["kind", "name"],
          properties: {
            kind: { const: "ref" },
            name: { type: "string" },
          },
          additionalProperties: false,
        },
      ],
    },
    ManifestOp: {
      oneOf: [
        { $ref: "#/$defs/ExecOp" },
        { $ref: "#/$defs/EvalOp" },
        { $ref: "#/$defs/ExecCompiledOp" },
        { $ref: "#/$defs/EvalCompiledOp" },
        { $ref: "#/$defs/DeclareOp" },
        { $ref: "#/$defs/AssignOp" },
        { $ref: "#/$defs/FuncDefOp" },
        { $ref: "#/$defs/ReturnOp" },
        { $ref: "#/$defs/IfOp" },
        { $ref: "#/$defs/LoopOp" },
        { $ref: "#/$defs/TryOp" },
        { $ref: "#/$defs/ThrowOp" },
        { $ref: "#/$defs/ParallelOp" },
        { $ref: "#/$defs/ConcatOp" },
        { $ref: "#/$defs/ImportOp" },
        { $ref: "#/$defs/NativeOp" },
        { $ref: "#/$defs/ChanOp" },
        { $ref: "#/$defs/SelectOp" },
        { $ref: "#/$defs/SpawnOp" },
        { $ref: "#/$defs/ResourceOp" },
        { $ref: "#/$defs/TableOp" },
        { $ref: "#/$defs/JobOp" },
        { $ref: "#/$defs/YieldOp" },
        { $ref: "#/$defs/AwaitOp" },
      ],
    },
    ExecOp: {
      type: "object",
      required: ["op", "runtime"],
      properties: {
        op: { const: "exec" },
        runtime: { type: "string" },
        code: { type: "string" },
        func: { type: "string" },
        args: { type: "array", items: { type: "string" } },
        captures: { $ref: "#/$defs/CaptureMap" },
      },
      additionalProperties: false,
    },
    EvalOp: {
      type: "object",
      required: ["op", "runtime", "bind"],
      properties: {
        op: { const: "eval" },
        runtime: { type: "string" },
        bind: { type: "string" },
        code: { type: "string" },
        func: { type: "string" },
        args: { type: "array", items: { type: "string" } },
        captures: { $ref: "#/$defs/CaptureMap" },
      },
      additionalProperties: false,
    },
    ExecCompiledOp: {
      type: "object",
      required: ["op", "lang", "code"],
      properties: { op: { const: "exec_compiled" }, lang: { type: "string" }, code: { type: "string" } },
      additionalProperties: false,
    },
    EvalCompiledOp: {
      type: "object",
      required: ["op", "lang", "code", "bind"],
      properties: { op: { const: "eval_compiled" }, lang: { type: "string" }, code: { type: "string" }, bind: { type: "string" } },
      additionalProperties: false,
    },
    DeclareOp: {
      type: "object",
      required: ["op", "bind", "mutable"],
      properties: { op: { const: "declare" }, bind: { type: "string" }, mutable: { type: "boolean" }, value: { $ref: "#/$defs/ManifestValue" }, from: { $ref: "#/$defs/ManifestOp" } },
      additionalProperties: false,
    },
    AssignOp: {
      type: "object",
      required: ["op", "target", "operator"],
      properties: { op: { const: "assign" }, target: { type: "string" }, operator: { type: "string" }, value: { $ref: "#/$defs/ManifestValue" }, from: { $ref: "#/$defs/ManifestOp" } },
      additionalProperties: false,
    },
    FuncDefOp: {
      type: "object",
      required: ["op", "name", "params", "body"],
      properties: {
        op: { const: "func_def" },
        name: { type: "string" },
        params: { type: "array", items: { type: "object" } },
        body: { type: "array", items: { $ref: "#/$defs/ManifestOp" } },
        generator: { type: "boolean" },
        async: { type: "boolean" },
        bodyRuntime: { type: "string" },
        source: { type: "string" },
        exports: { type: "array", items: { type: "string" } },
        requires: { type: "array", items: { type: "string" } },
        source_map: {
          type: "array",
          items: {
            type: "object",
            required: ["unit_line", "poly_line", "lines"],
            properties: {
              unit_line: { type: "number" },
              poly_line: { type: "number" },
              lines: { type: "number" },
            },
            additionalProperties: false,
          },
        },
        poly_file: { type: "string" },
      },
      additionalProperties: false,
    },
    ReturnOp: { type: "object", required: ["op"], properties: { op: { const: "return" }, value: { $ref: "#/$defs/ManifestValue" }, from: { $ref: "#/$defs/ManifestOp" } }, additionalProperties: false },
    IfOp: { type: "object", required: ["op", "condition", "then"], properties: { op: { const: "if" }, condition: {}, then: { type: "array" }, else: { type: "array" } }, additionalProperties: false },
    LoopOp: {
      type: "object",
      required: ["op", "body"],
      properties: {
        op: { const: "loop" },
        mode: { enum: ["while", "for", "infinite", "foreach"] },
        await: { type: "boolean" },
        test: {},
        condition: {},
        variable: { type: "string" },
        iterable: {},
        iterationMode: { enum: ["values", "keys", "auto"] },
        body: { type: "array" },
      },
      additionalProperties: false,
    },
    TryOp: { type: "object", required: ["op", "body"], properties: { op: { const: "try" }, body: { type: "array" }, catches: { type: "array" }, finallyBody: { type: "array" } }, additionalProperties: false },
    ThrowOp: { type: "object", required: ["op"], properties: { op: { const: "throw" }, value: { $ref: "#/$defs/ManifestValue" }, from: { $ref: "#/$defs/ManifestOp" } }, additionalProperties: false },
    ParallelOp: { type: "object", required: ["op", "branches"], properties: { op: { const: "parallel" }, branches: { type: "array" } }, additionalProperties: false },
    ConcatOp: { type: "object", required: ["op", "segments", "bind"], properties: { op: { const: "concat" }, segments: { type: "array" }, bind: { type: "string" } }, additionalProperties: false },
    ImportOp: { type: "object", required: ["op", "runtime", "module"], properties: { op: { const: "import" }, runtime: { type: "string" }, module: { type: "string" }, alias: { type: "string" }, names: { type: "array" } }, additionalProperties: false },
    NativeOp: { type: "object", required: ["op", "runtime", "code"], properties: { op: { const: "native" }, runtime: { type: "string" }, code: { type: "string" } }, additionalProperties: false },
    ChanOp: { type: "object", required: ["op", "action", "runtime"], properties: { op: { const: "chan" }, action: { enum: ["make", "send", "recv", "close"] }, runtime: { type: "string" }, bind: { type: "string" }, channel: { type: "string" }, size: { type: "number" }, value: { $ref: "#/$defs/ManifestValue" }, captures: { $ref: "#/$defs/CaptureMap" } }, additionalProperties: false },
    SelectOp: { type: "object", required: ["op", "cases"], properties: { op: { const: "select" }, cases: { type: "array" }, defaultBody: { type: "array" } }, additionalProperties: false },
    SpawnOp: { type: "object", required: ["op", "runtime", "code"], properties: { op: { const: "spawn" }, runtime: { type: "string" }, code: { type: "string" }, bind: { type: "string" }, captures: { $ref: "#/$defs/CaptureMap" } }, additionalProperties: false },
    ResourceOp: { type: "object", required: ["op", "action"], properties: { op: { const: "resource" }, action: { enum: ["open", "close"] }, runtime: { type: "string" }, bind: { type: "string" }, target: { type: "string" }, kind: { type: "string" }, disposer: { type: "string" }, code: { type: "string" }, value: { $ref: "#/$defs/ManifestValue" } }, additionalProperties: false },
    TableOp: { type: "object", required: ["op", "action"], properties: { op: { const: "table" }, action: { enum: ["export", "release"] }, runtime: { type: "string" }, bind: { type: "string" }, target: { type: "string" }, format: { type: "string" }, ownership: { type: "string" }, release: { type: "string" }, code: { type: "string" }, value: { $ref: "#/$defs/ManifestValue" } }, additionalProperties: false },
    JobOp: { type: "object", required: ["op", "action"], properties: { op: { const: "job" }, action: { enum: ["enqueue", "complete", "wait", "cancel"] }, runtime: { type: "string" }, bind: { type: "string" }, target: { type: "string" }, kind: { type: "string" }, payload: { $ref: "#/$defs/ManifestValue" }, value: { $ref: "#/$defs/ManifestValue" }, code: { type: "string" } }, additionalProperties: false },
    YieldOp: { type: "object", required: ["op"], properties: { op: { const: "yield" }, value: { $ref: "#/$defs/ManifestValue" }, from: { $ref: "#/$defs/ManifestOp" }, delegate: { type: "boolean" } }, additionalProperties: false },
    AwaitOp: { type: "object", required: ["op", "runtime", "from"], properties: { op: { const: "await" }, runtime: { type: "string" }, from: { $ref: "#/$defs/ManifestOp" }, bind: { type: "string" } }, additionalProperties: false },
    ManifestBridgeOp: { type: "object", required: ["binding", "op"], properties: { binding: { type: "string" }, op: { type: "string" }, from: { type: "string" }, to: { type: "string" }, meta: { type: "object" } }, additionalProperties: false },
    ManifestTypeSummary: { type: "object", required: ["crossings", "safe", "coerce", "check", "errors"], properties: { crossings: { type: "number" }, safe: { type: "number" }, coerce: { type: "number" }, check: { type: "number" }, errors: { type: "number" } }, additionalProperties: false },
    ManifestDiagnostic: { type: "object", required: ["severity", "code", "message"], properties: { severity: { enum: ["info", "warning", "error"] }, code: { type: "string" }, message: { type: "string" }, span: { type: "object" } }, additionalProperties: false },
  },
} as const;
