# AUTO-GENERATED by PolyScript cross-language stub emitter — DO NOT EDIT.
# Declares functions defined in another OmniVM runtime so that a Python
# type checker (e.g. mypy) can verify calls across the polyglot boundary.

from __future__ import annotations
from typing import Any

# ── defined in Rust ──
def lookup_tier(account_id: int) -> str | None: ...
def score_batch(account_ids: list[int], weight: float, normalize: bool) -> list[float]: ...
