// AUTO-GENERATED by PolyScript cross-language stub emitter — DO NOT EDIT.
// Declares functions defined in another OmniVM runtime so the TS/JS guest
// can type-check calls across the polyglot boundary.

// ── defined in Rust ──
export declare function lookup_tier(account_id: number): string | null;
export declare function score_batch(account_ids: number[], weight: number, normalize: boolean): number[];
