import { Lexer } from '../src/lexer';
import { Parser } from '../src/parser';
import { RuntimeResolver } from '../src/runtime-resolver';
import { ManifestCodeGenerator } from '../src/codegen-omnivm/manifest-generator';
import { DispatchManifest } from '../src/codegen-omnivm/manifest-types';
import {
  emitPyiStubs,
  emitDtsStubs,
  collectCrossLangFns,
  mapRustToPy,
  mapRustToTs,
  mapGoToPy,
  mapJsToPy,
} from '../src/codegen-omnivm/stub-emitter';

function compile(code: string): DispatchManifest {
  const lexer = new Lexer(code);
  const tokens = lexer.tokenize();
  const parser = new Parser(tokens, code);
  const ast = parser.parse();
  expect(parser.getErrors()).toHaveLength(0);
  const resolver = new RuntimeResolver();
  const annotated = resolver.resolve(ast, code);
  const gen = new ManifestCodeGenerator();
  return gen.generate(annotated);
}

// A mixed program: Rust functions with i64/f64/String/Vec/Option/HashMap/
// DataFrame/Dyn, a Go function, and a JS function — all called from Python.
const MIXED = `import re

fn analyze(values: Vec<i64>, label: String, ratio: f64, flag: bool) -> Vec<String> {
  vec![format!("{label}:{ratio}")]
}

fn maybe_name(id: i64) -> Option<String> {
  if id > 0 { Some(format!("u{id}")) } else { None }
}

fn make_frame() -> DataFrame {
  todo!()
}

fn summarize(frame: DataFrame, opts: Dyn) -> f64 {
  0.0
}

fn tally(counts: HashMap<String, i64>) -> i64 {
  0
}

func region_code(name) {
  return name.(string)
}

function shape_event(payload) {
  return { "ok": true }
}

result = analyze([1, 2, 3], "demo", 0.5, True)
name = maybe_name(7)
total = summarize(make_frame(), result)
n = tally({"a": 1})
rc = region_code("us")
ev = shape_event({"x": 1})
print(result)
`;

describe('stub-emitter: .pyi generation', () => {
  test('emits exact Python stub for a mixed Rust/Go/JS program', () => {
    const manifest = compile(MIXED);
    const expected = `# AUTO-GENERATED by PolyScript cross-language stub emitter — DO NOT EDIT.
# Declares functions defined in another OmniVM runtime so that a Python
# type checker (e.g. mypy) can verify calls across the polyglot boundary.

from __future__ import annotations
from typing import Any

# ── defined in Go ──
def region_code(name: Any) -> Any: ...

# ── defined in JavaScript ──
def shape_event(payload: Any) -> Any: ...

# ── defined in Rust ──
def analyze(values: list[int], label: str, ratio: float, flag: bool) -> list[str]: ...
def make_frame() -> Any: ...  # return: pandas.DataFrame / polars zero-copy
def maybe_name(id: int) -> str | None: ...
def summarize(frame: Any, opts: Any) -> float: ...  # frame: pandas.DataFrame / polars zero-copy
def tally(counts: dict[str, int]) -> int: ...
`;
    expect(emitPyiStubs(manifest)).toBe(expected);
  });
});

describe('stub-emitter: .d.ts generation', () => {
  test('emits exact TypeScript stub for a mixed Rust/Go/JS program', () => {
    const manifest = compile(MIXED);
    const expected = `// AUTO-GENERATED by PolyScript cross-language stub emitter — DO NOT EDIT.
// Declares functions defined in another OmniVM runtime so the TS/JS guest
// can type-check calls across the polyglot boundary.

// ── defined in Go ──
export declare function region_code(name: unknown): unknown;

// ── defined in JavaScript ──
export declare function shape_event(payload: unknown): unknown;

// ── defined in Rust ──
export declare function analyze(values: number[], label: string, ratio: number, flag: boolean): string[];
export declare function make_frame(): unknown;  // return: pandas.DataFrame / polars zero-copy
export declare function maybe_name(id: number): string | null;
export declare function summarize(frame: unknown, opts: unknown): number;  // frame: pandas.DataFrame / polars zero-copy
export declare function tally(counts: Record<string, number>): number;
`;
    expect(emitDtsStubs(manifest)).toBe(expected);
  });
});

describe('stub-emitter: determinism', () => {
  test('repeated emission is byte-identical', () => {
    const manifest = compile(MIXED);
    expect(emitPyiStubs(manifest)).toBe(emitPyiStubs(manifest));
    expect(emitDtsStubs(manifest)).toBe(emitDtsStubs(manifest));
  });

  test('functions are sorted by (runtime, name)', () => {
    const manifest = compile(MIXED);
    const fns = collectCrossLangFns(manifest);
    const keys = fns.map((f) => `${f.runtime}:${f.name}`);
    expect(keys).toEqual([...keys].sort());
  });

  test('python-bodied functions are excluded', () => {
    const manifest = compile(MIXED);
    const fns = collectCrossLangFns(manifest);
    expect(fns.every((f) => f.runtime !== 'python')).toBe(true);
    // The Python call sites (analyze(...), result = ...) are not declared.
    expect(fns.map((f) => f.name)).not.toContain('result');
  });

  test('generated mangling shims are not exported', () => {
    const manifest = compile(MIXED);
    const fns = collectCrossLangFns(manifest);
    expect(fns.some((f) => f.name.startsWith('__omnivm'))).toBe(false);
  });
});

describe('stub-emitter: fallbacks for missing / partial type info', () => {
  test('empty manifest produces a valid, header-only stub', () => {
    const empty: DispatchManifest = {
      version: 1,
      defaultRuntime: 'python',
      ops: [],
    };
    const pyi = emitPyiStubs(empty);
    expect(pyi).toContain('from typing import Any');
    expect(pyi).toContain('# (no cross-language functions found)');
    const dts = emitDtsStubs(empty);
    expect(dts).toContain('export {};');
  });

  test('func_def with no source and untyped params falls back to Any/unknown', () => {
    const manifest: DispatchManifest = {
      version: 1,
      defaultRuntime: 'python',
      ops: [
        {
          op: 'func_def',
          name: 'mystery',
          params: [{ name: 'a' }, { name: 'b' }],
          body: [],
          bodyRuntime: 'rust',
          // no `source` — types are unknowable
        } as any,
      ],
    };
    expect(emitPyiStubs(manifest)).toContain(
      'def mystery(a: Any, b: Any) -> Any: ...'
    );
    expect(emitDtsStubs(manifest)).toContain(
      'export declare function mystery(a: unknown, b: unknown): unknown;'
    );
  });

  test('does not crash on a malformed / partial Rust signature', () => {
    const manifest: DispatchManifest = {
      version: 1,
      defaultRuntime: 'python',
      ops: [
        {
          op: 'func_def',
          name: 'broken',
          params: [{ name: 'x' }],
          body: [],
          bodyRuntime: 'rust',
          source: 'fn broken(x: Vec<i64',
          exports: ['broken'],
        } as any,
      ],
    };
    expect(() => emitPyiStubs(manifest)).not.toThrow();
    expect(emitPyiStubs(manifest)).toContain('def broken(');
  });
});

describe('stub-emitter: Rust type mapping table', () => {
  test.each([
    ['i64', 'int'],
    ['u8', 'int'],
    ['usize', 'int'],
    ['isize', 'int'],
    ['f64', 'float'],
    ['f32', 'float'],
    ['bool', 'bool'],
    ['String', 'str'],
    ['&str', 'str'],
    ['char', 'str'],
    ['Vec<i64>', 'list[int]'],
    ['&[u8]', 'list[int]'],
    ['Option<String>', 'str | None'],
    ['HashMap<String, i64>', 'dict[str, int]'],
    ['BTreeMap<String, f64>', 'dict[str, float]'],
    ['(i64, String)', 'tuple[int, str]'],
    ['DataFrame', 'Any'],
    ['Dyn', 'Any'],
    ['omnivm::Dyn', 'Any'],
    ['()', 'None'],
    ['Vec<Option<i64>>', 'list[int | None]'],
  ])('rust %s -> py %s', (rust, py) => {
    expect(mapRustToPy(rust)).toBe(py);
  });

  test.each([
    ['i64', 'number'],
    ['f64', 'number'],
    ['bool', 'boolean'],
    ['String', 'string'],
    ['Vec<i64>', 'number[]'],
    ['Option<String>', 'string | null'],
    ['HashMap<String, i64>', 'Record<string, number>'],
    ['DataFrame', 'unknown'],
    ['Dyn', 'unknown'],
    ['Vec<Option<i64>>', '(number | null)[]'],
  ])('rust %s -> ts %s', (rust, ts) => {
    expect(mapRustToTs(rust)).toBe(ts);
  });
});

describe('stub-emitter: Go and JS type mapping tables', () => {
  test.each([
    ['int', 'int'],
    ['int64', 'int'],
    ['float64', 'float'],
    ['bool', 'bool'],
    ['string', 'str'],
    ['[]string', 'list[str]'],
    ['map[string]int', 'dict[str, int]'],
    ['interface{}', 'Any'],
  ])('go %s -> py %s', (go, py) => {
    expect(mapGoToPy(go)).toBe(py);
  });

  test.each([
    ['number', 'float'],
    ['string', 'str'],
    ['boolean', 'bool'],
    ['any', 'Any'],
    ['number[]', 'list[float]'],
  ])('js %s -> py %s', (js, py) => {
    expect(mapJsToPy(js)).toBe(py);
  });
});
